import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Retire the `transfer_ownership` capability (T-0170).
 *
 * This is a DATA change, not a schema change, against a LIVE production
 * database (live since 2026-07-20). It removes exactly one thing: every
 * `role_permissions` row whose `capability` is the string `'transfer_ownership'`
 * — six rows on the shipped default matrix (one per `member_role`), plus any an
 * admin edited. No DDL, no column drop, no other table touched.
 *
 * A migration is required because the seeder cannot do it: `capability` is a
 * plain `varchar(60)` (not a MySQL ENUM), so nothing schema-level referenced the
 * value, and `seedRolePermissions` provisions insert-only and never deletes. The
 * DELETE is naturally idempotent — 0 rows affected on a database that never had
 * them, so it is safe on a fresh install and on a re-run.
 *
 * Leaving the rows would be harmless at runtime (`buildMatrix` ignores rows for
 * capabilities outside the enum), but they would be invisible, un-editable and
 * un-auditable dead grants — exactly the state that makes a later re-use of the
 * key silently resurrect stale permissions.
 *
 * `down()` DOES NOT restore the grants, deliberately. The pre-migration state
 * was per-regiment editable data, and this migration does not record what it
 * deleted, so re-inserting a hardcoded Owner row would be a fabrication rather
 * than an inverse — it would also have to invent an `id` (the column is
 * `char(12)`, generated by ShortIdEntity, so raw SQL must supply one) and would
 * silently drop any non-default grant an admin had made. Rolling this migration
 * back only makes sense alongside reverting the code that deleted
 * `Capability.TransferOwnership`; at that point `seedRolePermissions` re-inserts
 * the default rows on the next `seed:prod` run, which is the honest recovery
 * path.
 */
export class RetireTransferOwnership1784900000000 implements MigrationInterface {
  name = 'RetireTransferOwnership1784900000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM \`role_permissions\` WHERE \`capability\` = 'transfer_ownership'`,
    );
  }

  public down(): Promise<void> {
    // Intentionally a no-op — see the class doc block. The grants are restored
    // by re-running the role-permission seeder against a codebase that still
    // declares the capability, not by this migration.
    return Promise.resolve();
  }
}
